import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import JobPageNav from "./components/JobPageNav";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Job Tracker App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col px-4 sm:px-6 lg:px-8 py-6 max-w-6xl mx-auto">
        <AuthProvider>
          <JobPageNav />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
